ourcar/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
]

ourcar/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')), 
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
    

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ourcar/pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

app_name = 'pybo'

urlpatterns = [ 
   # base_views.py
    path('',
         base_views.index, name='index'),
     path('my_page/', base_views.my_page, name='my_page'),

    path('<int:question_id>/',
         base_views.detail, name='detail'),

    # question_views.py
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
    
    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', 
         answer_views.answer_vote, name='answer_vote'),

    
]   

ourcar/pybo/views/base_views.py
# pybo/views/base_views.py

from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from ..models import Question
from common.models import TestSangmin
from ..forms import ProfileImageForm

# 메인 질문 리스트 + 페이지네이션
def index(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    
    paginator = Paginator(question_list, 12)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'pybo/question_list.html', context)

# 질문 상세 보기
def detail(request, question_id):
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url='common:login')
def my_page(request):
    user = request.user
    
    # 사용자에게 연결된 test_sangmin 객체 가져오기
    try:
        test_sangmin_instance = TestSangmin.objects.get(id=user.id)
    except TestSangmin.DoesNotExist:
        test_sangmin_instance = None
        
    liked_questions = Question.objects.filter(voter=user)
    
    # 페이지네이션 추가
    page = request.GET.get('page', 1)  # 현재 페이지 번호
    paginator = Paginator(liked_questions, 8)  # 페이지당 12개씩 보여주기
    page_obj = paginator.get_page(page)
    
    # 사용자의 프로필 이미지를 가져옵니다.
    profile_image = user.profile_image
    if request.method == 'POST':
        print("post----------------------")
        form = ProfileImageForm(request.POST, request.FILES, instance=request.user)
        print(request.FILES)
        if form.is_valid():
            form.save()
            return render(request, 'pybo/my_page.html', {'liked_questions': page_obj, 'test_sangmin_instance': test_sangmin_instance, 'profile_image': profile_image, 'profile_image_form': form})  # Render the user's profile page
            # return redirect("/")  # Render the user's profile page
    else:
        form = ProfileImageForm(instance=request.user)
        print("get----------------------")

    return render(request, 'pybo/my_page.html', {'liked_questions': page_obj, 'test_sangmin_instance': test_sangmin_instance, 'profile_image': profile_image, 'profile_image_form': form})
    
# @login_required(login_url='common:login')
# def upload_profile_image(request):
#     if request.method == 'POST':
#         form = ProfileImageForm(request.POST, request.FILES, instance=request.user)
#         if form.is_valid():
#             form.save()
#             return render(request, 'my_page')  # Render the user's profile page
#     else:
#         form = ProfileImageForm(instance=request.user)
#     return render(request, 'pybo/upload_profile_image.html', {'profile_image_form': form})

ourcar/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'style1.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->


    <title>Hello, pybo!</title>
</head>
<body>
<!-- 네비게이션바 -->
<div>
{% include "navbar.html" %}
</div>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->

<script src="{% static 'bootstrap.min.js' %}"></script>
<script src="{% static 'javascripts.js' %}"></script>

<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

ourcar/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

ourcar/templates/navbar.html
<!-- 네비게이션바 -->
<div>
<nav class="navbar  fixed-top navbar-expand-lg navbar-light bg-light">
    <div class="test container-fluid  navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">아워카</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <li><a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a></li>
                    <li><a class="nav-link" href="{% url 'pybo:my_page' %}">마이페이지</a></li>

                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>