ourcar/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
]

ourcar/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')), 
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
    

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ourcar/pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

app_name = 'pybo'

urlpatterns = [ 
   # base_views.py
    path('',
         base_views.index, name='index'),
     path('my_page/', base_views.my_page, name='my_page'),

    path('<int:question_id>/',
         base_views.detail, name='detail'),

    # question_views.py
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
    
    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', 
         answer_views.answer_vote, name='answer_vote'),

    
]   

ourcar/common/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser



class TestSangmin(models.Model):
    id = models.AutoField(primary_key=True)
    seq = models.CharField(max_length=255, blank=True, null=True)
    interior_am = models.DecimalField(max_digits=18, decimal_places=0, blank=True, null=True)
    insuhos_am = models.DecimalField(max_digits=18, decimal_places=0, blank=True, null=True)
    offedu_am = models.DecimalField(max_digits=18, decimal_places=0, blank=True, null=True)
    trvlec_am = models.DecimalField(max_digits=18, decimal_places=0, blank=True, null=True)
    fsbz_am = models.DecimalField(max_digits=18, decimal_places=0, blank=True, null=True)
    svcarc_am = models.DecimalField(max_digits=18, decimal_places=0, blank=True, null=True)
    dist_am = models.DecimalField(max_digits=18, decimal_places=0, blank=True, null=True)
    plsanit_am = models.DecimalField(max_digits=18, decimal_places=0, blank=True, null=True)
    clothgds_am = models.DecimalField(max_digits=18, decimal_places=0, blank=True, null=True)
    auto_am = models.DecimalField(max_digits=18, decimal_places=0, blank=True, null=True)
    car_price = models.DecimalField(max_digits=18, decimal_places=0, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'test_sangmin'

class CustomUser(AbstractUser):
    phone_number = models.CharField(max_length=20)
    profile_image = models.ImageField(upload_to='profile_images', blank=True, null=True)
    test_sangmin = models.OneToOneField(TestSangmin, on_delete=models.CASCADE, related_name='custom_user', blank=True, null=True)

ourcar/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")
    phone_number = forms.CharField(label="전화번호")  # 전화번호 필드 추가

    class Meta:
        model = CustomUser  
        fields = ("username", "password1", "password2", "email", "phone_number")

ourcar/common/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from common.forms import CustomUserForm  # CustomUserForm을 사용하기 위해 import

def logout_view(request):
    logout(request)
    return redirect('index')

def signup(request):
    if request.method == "POST":
        form = CustomUserForm(request.POST)  # CustomUserForm 사용
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = CustomUserForm()  # CustomUserForm 사용
    return render(request, 'common/signup.html', {'form': form})

ourcar/templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

ourcar/templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post" action="{% url 'common:signup' %}" class="border p-4 rounded shadow-sm">
                {% csrf_token %}
                {% include "form_errors.html" %}
                <div class="mb-3">
                    <label for="username" class="form-label">사용자 이름</label>
                    <input type="text" class="form-control" name="username" id="username"
                           value="{{ form.username.value|default_if_none:'' }}">
                </div>
                <div class="mb-3">
                    <label for="password1" class="form-label">비밀번호</label>
                    <input type="password" class="form-control" name="password1" id="password1"
                           value="{{ form.password1.value|default_if_none:'' }}">
                </div>
                <div class="mb-3">
                    <label for="password2" class="form-label">비밀번호 확인</label>
                    <input type="password" class="form-control" name="password2" id="password2"
                           value="{{ form.password2.value|default_if_none:'' }}">
                </div>
                <div class="mb-3">
                    <label for="email" class="form-label">이메일</label>
                    <input type="text" class="form-control" name="email" id="email"
                           value="{{ form.email.value|default_if_none:'' }}">
                </div>
                <div class="mb-3">
                    <label for="phone_number" class="form-label">전화번호</label>
                    <input type="text" class="form-control" name="phone_number" id="phone_number"
                           value="{{ form.phone_number.value|default_if_none:'' }}">
                </div>

                <!-- 전화번호 양식 자동 입력 스크립트 -->
                <script>
                    document.getElementById('phone_number').addEventListener('input', function (e) {
                        var x = e.target.value.replace(/\D/g, '').match(/(\d{0,3})(\d{0,4})(\d{0,4})/);
                        e.target.value = !x[2] ? x[1] : x[1] + '-' + x[2] + (x[3] ? '-' + x[3] : '');
                    });
                </script>
                
                <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">생성하기</button>
                </div>            </form>
        </div>
    </div>
</div>
{% endblock %}